### ISSUE TITLE
wavefront_alert resource keeps creating new alerts / destroy doesn't destroy the alert but blanks out state

### ISSUE THREAD

**Issue by ognnaot** [spaceapegames/terraform-provider-wavefront#25] opened 2018-02-23 17:26 UTC
I created an alert.  terraform plan, terraform apply.  Alert gets created.  With no changes to config, terraform plan.  It says it's refreshing the ID of the alert (ID matches correctly).  terraform plan output is to create a new alert again.  terraform apply will create a new alert with a new ID, resulting in a duplicate alert.

terraform destroy returns nothing to be destroyed but if I enter yes, the state is destroyed but the alerts still remain in wavefront.

using terraform v0.11.3

**Comment by ognnaot** [comment] 2018-02-23 18:31
This may have been resolve with go-wavefront updates...I will try rebuilding.

**Comment by nathmclean** [comment] 2018-02-23 19:00
@ognnaot - We've seen issues whereby the alert is not available immediately after creation; this was due to using a 'search' to perform the lookup, which is cached -  the cache takes a second to update. 

I raised a case with Wavefront, they can't see anything wrong, but we're in the process of updating the provider to use the GET /alert/{id} endpoint (hence the go-wavefront update to implement the get function).

We've only seen this process when the plan/update/delete is performed immediately (sub-second) after the apply.

**Comment by ognnaot** [comment] 2018-02-23 19:14
I've waited minutes and even to the next day and my tests still see the above symptoms.  Maybe my environment is caching much longer.
I've pulled in the go-wavefront changes and trying to do some patching on my end.  Looks like the Find functions can be removed since I don't see them being used after the Get function added.

**Comment by louism517** [comment] 2018-02-24 09:28
The find functions are still useful, they allow searching on any criteria. For instance you may wish to search for all Alerts which are 'Snoozed'.

This is a strange issue. We use this provider to manage all of our Wavefront alerts (on the same version of terraform as yourself), without issue.

Does the WF token you are using definitely have sufficient permissions, and does it get passed in correctly each time? 

Could you provide specific steps to reproduce the problem, and we can investigate our end?

**Comment by nathmclean** [comment] 2018-02-26 12:22
@ognnaot I've just had #27 merged to start using 'get' over 'find' and this has alleviated the problems we were seeing.

v1.0.2 has these changes. Hopefully, this solves your problem too.

Thanks for your PR, the changes are essentially what I implemented (although there were some tests that also needed to be updated).

**Closed** 2018-02-27 10:19 UTC
